[profile.default]
    src = "src"
    out = "out"
    libs = ["lib"]
    evm_version = 'paris'
    build_info = true
    via_ir = true
    optimizer = true

remappings = [
    '@layerzerolabs/=node_modules/@layerzerolabs/',
    '@openzeppelin/=node_modules/@openzeppelin/',
]

# LZ does not have v2 endpoints on goerli
[rpc_endpoints]
    sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
    arbitrum_sepolia = "https://arb-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
    polygon_mumbai = "https://polygon-mumbai.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
    polygon_amoy = "https://polygon-amoy.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
    bnb_testnet = "https://polygon-mumbai.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
    mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
    polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
    base_sepolia = "https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[etherscan]
    arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}" }
    sepolia = { key = "${ETHERSCAN_API_KEY}" }
    mainnet = { key = "${ETHERSCAN_API_KEY}" }
    polygon = { key = "${POLYGONSCAN_API_KEY}" }
    polygon_mumbai = { key = "${POLYGONSCAN_API_KEY}" }
    polygon_amoy = { key = "${POLYGONSCAN_API_KEY}", url = "https://api-amoy.polygonscan.com/api" }
    base_sepolia = { key = "${BASESCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
